#!/usr/bin/env python3
"""
CLI-Based Intersection Collection Demo

This demo demonstrates using the CLI to collect and analyze intersected topics.
It actually fetches from RSS feeds and exports digests.

Usage:
    uv run python examples/topics/demo_cli_intersection.py
"""

import subprocess
import json
from pathlib import Path
from datetime import datetime


def run_cli_command(cmd):
    """Run a CLI command and return output."""
    print(f"\n{'=' * 80}")
    print(f"Running: {' '.join(cmd)}")
    print('=' * 80)
    
    result = subprocess.run(cmd, capture_output=True, text=True)
    
    if result.returncode == 0:
        print(result.stdout)
        return result.stdout
    else:
        print(f"Error: {result.stderr}")
        return None


def demo_cli_stats():
    """Show current database statistics."""
    print("\n" + "=" * 80)
    print("STEP 1: Current Database Statistics")
    print("=" * 80)
    
    cmd = ["uv", "run", "python", "-m", "ai_news.cli", "stats"]
    run_cli_command(cmd)


def demo_cli_collect_uk():
    """Collect news from UK region."""
    print("\n" + "=" * 80)
    print("STEP 2: Collecting UK AI News")
    print("=" * 80)
    
    cmd = ["uv", "run", "python", "-m", "ai_news.cli", "collect", "--region", "uk", "--max", "10"]
    output = run_cli_command(cmd)
    return output is not None


def demo_cli_intersection_ai_insurance():
    """Search for AI + Insurance intersection."""
    print("\n" + "=" * 80)
    print("STEP 3: Searching for AI + Insurance Intersection")
    print("=" * 80)
    
    # Use intersection search
    cmd = [
        "uv", "run", "python", "-m", "ai_news.enhanced_cli",
        "intersection", "AI", "Insurance",
        "--region", "uk",
        "--limit", "5",
        "--details"
    ]
    output = run_cli_command(cmd)
    return output


def demo_cli_list_recent():
    """List recent articles."""
    print("\n" + "=" * 80)
    print("STEP 4: Listing Recent Articles")
    print("=" * 80)
    
    cmd = ["uv", "run", "python", "-m", "ai_news.cli", "list", "--limit", "5"]
    run_cli_command(cmd)


def demo_cli_export_digest():
    """Export digest (simulated - saves output to file)."""
    print("\n" + "=" * 80)
    print("STEP 5: Exporting Digest")
    print("=" * 80)
    
    # Get AI + Insurance articles
    cmd = [
        "uv", "run", "python", "-m", "ai_news.enhanced_cli",
        "intersection", "AI", "Insurance",
        "--region", "uk",
        "--limit", "10"
    ]
    
    result = subprocess.run(cmd, capture_output=True, text=True)
    
    if result.returncode == 0:
        # Save to digest file
        digest_dir = Path("digests")
        digest_dir.mkdir(exist_ok=True)
        
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        digest_file = digest_dir / f"cli_ai_insurance_uk_{timestamp}.md"
        
        # Create markdown digest
        digest_content = f"""# AI + Insurance News Digest (CLI-Based)

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Source:** CLI Intersection Search
**Topic Intersection:** AI + Insurance
**Region:** United Kingdom

---

## CLI Command Used

```bash
{' '.join(cmd)}
```

---

## Results

```
{result.stdout}
```

---

## Collection Notes

- This digest was generated using the CLI interface
- Articles are fetched from configured RSS feeds
- Intersection filtering ensures all keyword categories match
- Regional filtering applied: UK

---
*Generated by AI News Collector - CLI Interface*
"""
        
        digest_file.write_text(digest_content)
        print(f"\n✅ Digest exported to: {digest_file}")
        print(f"   Size: {len(digest_content)} characters")
        return True
    else:
        print(f"❌ Failed to generate digest: {result.stderr}")
        return False


def demo_cli_multi_keyword_search():
    """Demonstrate multi-keyword search."""
    print("\n" + "=" * 80)
    print("STEP 6: Multi-Keyword Search Demo")
    print("=" * 80)
    
    cmd = [
        "uv", "run", "python", "-m", "ai_news.enhanced_cli",
        "multi", "machine learning", "healthcare",
        "--region", "us",
        "--limit", "3"
    ]
    run_cli_command(cmd)


def main():
    """Run complete CLI-based demo."""
    print("\n" + "=" * 80)
    print(" CLI-BASED INTERSECTION COLLECTION DEMO")
    print(" Using actual CLI commands to collect and analyze news")
    print("=" * 80)
    
    print("\n📋 This demo will:")
    print("   1. Show current database statistics")
    print("   2. Collect news from UK region")
    print("   3. Search for AI + Insurance intersection")
    print("   4. List recent articles")
    print("   5. Export digest to markdown file")
    print("   6. Demonstrate multi-keyword search")
    
    # Run demo steps
    demo_cli_stats()
    success = demo_cli_collect_uk()
    
    if success:
        demo_cli_intersection_ai_insurance()
        demo_cli_list_recent()
        demo_cli_export_digest()
        demo_cli_multi_keyword_search()
    else:
        print("\n⚠️  Collection failed, skipping some steps")
    
    print("\n" + "=" * 80)
    print(" ✅ DEMO COMPLETED")
    print("=" * 80)
    print("\n💡 Tips:")
    print("   - Check digests/ for exported markdown files")
    print("   - Use 'uv run python -m ai_news.enhanced_cli --help' for more commands")
    print("   - Use 'uv run python -m ai_news.cli collect' to collect more news")


if __name__ == "__main__":
    main()
